# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eab59b3efe0b4b47ece5b9834a3242a622b421b9b00751a11405a395aeada1554fb1def93432eaa0c743b0f84c55789f98f493d601c03a109f38767c0b4b1f9

test:
  secret_key_base: 97f970eef120df855c9fa806bd7353512f64c43fb66ade2277c713294c7fd2f847556c36e2e1575be9def01c073ae9aecb74763589293b03c254e684d7290c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
